export const USER_REGISTRATION: string = 'USER_REGISTRATION'
export const USER_LOGOUT: string = 'USER_LOGOUT'
export const SET_AUTH: string = 'SET_AUTH'
export const USER_LOGIN: string = 'USER_LOGIN'
export const SET_USER: string = 'SET_USER'